plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.2'
    // 인텔리제이(IntelliJ)가 Gradle 8.8 이상의 아주 최신 버전으로 기본 세팅되어 동작하고 있기 때문에 버전업
    // 기존 1.1.0 -> 1.1.6
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'me.kimchangju' // 지정한 그룹 이름
version = '1.0-SNAPSHOT'

// 최신 그레이들(Gradle) 버전의 문법 규칙이 변경되면서 책과 다른 부분
java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // 추가 3.2.1 스프링 데이터 JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.h2database:h2' // 인메모리 데이터베이스
    compileOnly 'org.projectlombok:lombok' // 롬복
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
}

test {
    useJUnitPlatform()
}